### ISSUE TITLE
Document disterl encryption

### ISSUE THREAD

**Issue by lukebakken** [basho/basho_docs#1058]
Erlang documentation of the feature: http://www.erlang.org/doc/apps/ssl/ssl_distribution.html

From the `vm.args` file:

```
## Begin SSL distribution items, DO NOT DELETE OR EDIT THIS COMMENT

## To enable SSL encryption of the Erlang intra-cluster communication,
## un-comment the three lines below and make certain that the paths
## point to correct PEM data files.  See docs TODO for details.

## -proto_dist inet_ssl
## -ssl_dist_opt client_certfile "./etc/erlclient.pem"
## -ssl_dist_opt server_certfile "./etc/erlserver.pem"

## End SSL distribution items, DO NOT DELETE OR EDIT THIS COMMENT
```

Mailing list thread:
http://lists.basho.com/pipermail/riak-users_lists.basho.com/2014-February/014750.html

See ticket 7852.

**Comment by benbro** [comment]
This issue is closed but I can't find explanation on internode communication using SSL in the docs.
https://github.com/basho/riak/issues/509

**Comment by TheOnlyRew** [comment]
Hi @benbro. Does this page answer your questions?
http://docs.basho.com/riak/latest/dev/advanced/client-security/

**Comment by benbro** [comment]
Does client-side security also applies to internode communication?
riak config has listener.https.internal but the page you linked to says ssl only work with protobuf, so what does https means?

Maybe this page has better info
http://docs.basho.com/riak/latest/ops/running/authz/#Enabling-SSL

**Comment by TheOnlyRew** [comment]
@benbro, my apologies for sending you to a stale page. You're correct that cert-based client communications can operate over HTTPS, and I've created a new issue (#1892) to track and resolve the incorrect information in the /advanced/client-security/ pages.

As for configuring Distributed Erlang to use SSL for inter-node communications, no, setting up client authorization does not configure inter-node communications to run over SSL. After doing some digging, it looks to me like this issue was closed because configuring Erlang to communicate over SSL causes Riak to fail at startup. Until https://github.com/basho/riak/issues/509, https://github.com/basho/node_package/pull/183, and https://github.com/basho/riak/pull/728 are reviewed, merged, resolved, and released, documenting this feature is a moot point. Changes need to be made to the `env.sh`, `riak`, and `riak-admin` shell scripts, and such modifications fall outside the scope of our official documentation.

It should be possible to manually modify the shell scripts that are currently preventing Riak from starting up while using SSL for inter-node communications, though. If you need to do this for your usecase, I'd recommend asking for additional information through our mailing list, or on our Freenode IRC channel.
