### ISSUE TITLE
Erlang build instructions revamp [JIRA: PMT-155]

### ISSUE THREAD

**Issue by lukebakken** [basho/basho_docs#1465]
The instructions given here:
http://docs.basho.com/riak/latest/ops/building/installing/erlang/#Install-using-kerl

Should exactly match the build flags we use here:
https://github.com/basho/basho_buildbot/blob/master/erlscripts/install_patched_r16.sh

Ensure build pre-reqs are complete as well (like `autoconf` on ubuntu)

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by TheOnlyRew** [comment]
Instructions for building on Ubuntu (and likely other platforms) is also incorrect. `./configure` is no longer shipped pre-generated. Instead, the `./otp_build` script is shipped. Rather than the `./configure && make && sudo make install` combo, users should be running `./otp_build autoconf && ./otp_build configure && sudo make install`.

We should also homogenize the use of `wget` and `curl` -- it's inconsistent between [Installing Erlang] and the [Five-Minute Install].

[Installing Erlang]: http://docs.basho.com/riak/latest/ops/building/installing/erlang/#Installing-on-GNU-Linux
[Five-Minute Install]: http://docs.basho.com/riak/latest/quickstart/#Install-Riak

**Comment by laurenrother** [comment]
@lukebakken and @TheOnlyRew Do @erjohnson 's recent updates to the [Erlang instructions](https://github.com/basho/basho_docs/pull/1740) address these concerns?

**Comment by lukebakken** [comment]
Very impressive set of updates thank you all :fish_cake:

**Comment by laurenrother** [comment]
:+1:
