### ISSUE TITLE
🚀⚠️💥 [JIRA: DOC-291]

### ISSUE THREAD

**Issue by laurenrother** [basho/basho_docs#1991]
- [x] docs.basho.com is without a stylesheet. This happened sometime overnight. A refresh works for some folks, and not for others. LR is one of the others.
- [x] It also appears that the stylesheet is not being applied to some (but not all) pages. Per Shaun McVey: "Certain pages are just text, others are fine." He suspects: "Looks like missing css files (http://docs.basho.com/riak/2.1.3/css/all.css?1459957163 gives me a 404)" Check the Docs channel scrollback for even more info.
- [x] If not a stylesheet issue, it may be a CDN issue: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html
- [x] A 404 has been reported on http://docs.basho.com/riak/ts/latest
- [x] robots.txt from staging was published to the live site and is blocking Google from indexing (which has killed Search).
- [x] This page is entirely filler: http://docs.basho.com/riak/kv/2.1.3/using/reference/architecture/.
- [x] ^^^ Now it 404s.
- [x] [private_docs Issue #181](https://github.com/basho/private_basho_docs/issues/181#)
- [x] There appears to be problems with how code examples are rendering. 
-    ~~Level 2 and Level 3 headings are rendered using the same font & size - seems strange, as only Level 2 are shown in the page Contents on the top of the page. For example, see: http://stage.docs.basho.com/riak/kv/2.1.3/learn/why-riak-kv/~~
- [x] Some pages, like http://stage.docs.basho.com/riak/kv/2.1.3/using/troubleshooting/ - missing content
- [x] Did we make redirects for riakee? We need to. 

- [ ] [Post Launch Tasks](https://github.com/basho/private_basho_docs/issues/144)

**Comment by Basho-JIRA** [comment]
After a full day of chasing broken stylesheets, failing index redirects, and other assorted problems, we've found ourselves here: 

1. Google Index is running on the new site, which should solve some search problems. 
2. We are running into massive problems with deploying. The updated docs will appear on the S3 server but will not populate to the docs. This is due to either: 
    a. Severe CDN lag due to a ton of work done in the last 24 hours, or 
    b. Some problem in our deployment chain. 
Only time will tell whether a.) or b.) is the case. If it is still an issue tomorrow, we will schedule a meeting with DevOps to discuss our options. 
3. Redirects are an ongoing problem. While all the ones we tested on staging worked on staging, they are failing massively in live deployment. We have no idea why just yet.
4. The above 3 issues have kept us from all Post-Launch tasks, for the most part. 
5. Oh, and we launched Riak KV 2.1.4 today NBD.  

***[posted via JIRA by Lauren Rother]***

**Comment by Basho-JIRA** [comment]
After a full day of chasing broken stylesheets, failing index redirects, and other assorted problems, we've found ourselves here: 

1. Google Index is running on the new site, which should solve some search problems. 
2. We are running into massive problems with deploying. The updated docs will appear on the S3 server but will not populate to the live site. This is due to either: 
    a. Severe CDN lag due to a ton of work done in the last 24 hours, or 
    b. Some problem in our deployment chain. 
Only time will tell whether a.) or b.) is the case. If it is still an issue tomorrow, we will schedule a meeting with DevOps to discuss our options. 
3. Redirects are an ongoing problem. While all the ones we tested on staging worked on staging, they are failing massively in live deployment. We have no idea why just yet.
4. The above 3 issues have kept us from all Post-Launch tasks, for the most part. 
5. Oh, and we launched Riak KV 2.1.4 today NBD.  

***[posted via JIRA by Lauren Rother]***

**Comment by Basho-JIRA** [comment]
After a full day of chasing broken stylesheets, failing index redirects, and other assorted problems, we've found ourselves here: 

1. Google Index is running on the new site, which should solve some search problems. 
2. We are running into massive problems with deploying. The updated docs will appear on the S3 server but will not populate to the live site. This is due to either: 

        a. Severe CDN lag due to a ton of work done in the last 24 hours, or 
        b. Some problem in our deployment chain. 
Only time will tell whether a.) or b.) is the case. If it is still an issue tomorrow, we will schedule a meeting with DevOps to discuss our options. 
3. Redirects are an ongoing problem. While all the ones we tested on staging worked on staging, they are failing massively in live deployment. We have no idea why just yet.
4. The above 3 issues have kept us from all Post-Launch tasks, for the most part. 
5. Oh, and we launched Riak KV 2.1.4 today NBD.  

***[posted via JIRA by Lauren Rother]***

**Comment by Basho-JIRA** [comment]
After a full day of chasing broken stylesheets, failing index redirects, and other assorted problems, we've found ourselves here: 

1. Google Index is running on the new site, which should solve some search problems. 
2. We are running into massive problems with deploying. The updated docs will appear on the S3 server but will not populate to the live site. This is due to either: 
bq.         a. Severe CDN lag due to a ton of work done in the last 24 hours, or 
bq.         b. Some problem in our deployment chain. 
Only time will tell whether a.) or b.) is the case. If it is still an issue tomorrow, we will schedule a meeting with DevOps to discuss our options. 
3. Redirects are an ongoing problem. While all the ones we tested on staging worked on staging, they are failing massively in live deployment. We have no idea why just yet.
4. The above 3 issues have kept us from all Post-Launch tasks, for the most part. 
5. Oh, and we launched Riak KV 2.1.4 today NBD.  

***[posted via JIRA by Lauren Rother]***

**Comment by Basho-JIRA** [comment]
After a full day of chasing broken stylesheets, failing index redirects, and other assorted problems, we've found ourselves here: 

1. Google Index is running on the new site, which should solve some search problems. 
2. We are running into massive problems with deploying. The updated docs will appear on the S3 server but will not populate to the live site. This is due to either: 
bq.         a. Severe CDN lag due to a ton of work done in the last 24 hours, or 
bq.         b. Some problem in our deployment chain. 
Only time will tell whether a.) or b.) is the case. If it is still an issue tomorrow, we will schedule a meeting with DevOps to discuss our options. 
3. Redirects are an ongoing problem. While all the ones we tested on staging worked on staging, they are failing massively in live deployment. We have no idea why just yet.
4. The above 3 issues have kept us from all Post-Launch tasks, for the most part. 
5. Oh, and we launched Riak KV 2.1.4 today NBD.  

***[posted via JIRA by Lauren Rother]***

**Comment by TheOnlyRew** [comment]
Level 2 and Level 3 headings are rendered using the same font, but are not the same size,

```
  h2 {
    @extend .sans;
    font-size   : 200%;
    line-height : 1.2;
    padding     : .8em 0 .1em 0;
. . .

  h3 {
    @extend .sans;
    font-size   : 175%;
    padding-top : .8em;
```

We can open up another issue to discuss whether or not that's enough of a difference, but it makes no sense for that opinion to be sorted with more critical content/CDN/indexing/redirection issues. Similarly, H2 headers have always been the only ones to be included in generated ToCs, and I see no reason for that to change.

**Comment by TheOnlyRew** [comment]
The riak/2.1.3/css/all.css* file no longer exists in S3, so that should actually be a 404. The actual issue there was that the new stylesheets weren't propagating through the CDNs. I believe that to be resolved at this point, and so I'm going to tentatively check off that issue.

**Comment by TheOnlyRew** [comment]
riak/kv/2.1.3/using/troubleshooting/ is no longer missing content. Are there any other pages seeing this class of issue?

If so, please make note of them, and un-check the relevant box.

**Comment by TheOnlyRew** [comment]
I'm fairly certain http://docs.basho.com/riak/kv/2.1.3/using/reference/architecture/ should 404.

It's the last entry in our [IgnoreFiles list](https://github.com/basho/basho_docs/blob/master/config.yaml#L12-L77), so the file isn't being written to public/ for deployment. Also, the [file itself is empty](https://github.com/basho/basho_docs/blob/master/content/riak/kv/2.1.3/using/reference/architecture.md).

**Comment by laurenrother** [comment]
All of the immediate issues have been addressed. Further issues will be tracked separately.

**Comment by Basho-JIRA** [comment]
***Update:***
We spent the day investigating two problems: Site deploy lag and 404s. Updates as follows:
1. Google Index is running on the new site, which should solve some search problems.
-> Google indexed the new site and the old site. Combined with the the CDN lag, this created garbled new URLs which, of course, 404'd. The old site pages have been added to robots.txt and blocked from indexing. We will run Google index tomorrow when the CDNs have caught up. 
2. We are running into massive problems with deploying. The updated docs will appear on the S3 server but will not populate to the live site.
-> See [DOC-295] for updates on CDNs. tl;dr we updated some configurations and the deployment behavior, but the CDNs are lagging and we have to wait for them to catch up.
3. Redirects are an ongoing problem. While all the ones we tested on staging worked on staging, they are failing massively in live deployment. We have no idea why just yet.
->  See [DOC-297] for more information, but tl;dr there were about 4 different things causing 404s and we have addressed all of them and are standing by to fix any others that come up. 
4. The above 3 issues have kept us from all Post-Launch tasks, for the most part.
-> We will be attending to all Post Launch tasks (https://github.com/basho/private_basho_docs/issues/144) tomorrow now that the immediate worries and concerns are handled.  

***[posted via JIRA by Lauren Rother]***

**Comment by Basho-JIRA** [comment]
**Update:**
1. We have submitted an updated sitemap.xml to Google and reissued an index request. This should fix search problems and URL mashups.
2. The CDN lag is getting better hour by hour. At this point, we've done all we can to optimize our CloudFront, S3, and deployment configuration, only time will sort out the CDN holdup, which it is doing slowly but surely.
3. The redirect work continues and should be complete tomorrow. Eric will be catching up with Sean in CliServ tomorrow to put together scripts to check redirects and download page health. 
4. We have begun the Post-Launch tasks ((https://github.com/basho/private_basho_docs/issues/144) in earnest.

I anticipate closing this issue entirely tomorrow. 

***[posted via JIRA by Lauren Rother]***

**Comment by Basho-JIRA** [comment]
*Update:*
1. I verified yesterday that our remediation efforts were a.) correct and b.) the length and breadth of what we can do. Google is churning away on our sitemap and index. Justin also submitted our sitemap for On Demand indexing, which will add 500 pages to Google's index immediately. Now it is all waiting and watching our numbers.
2. The CDN lag seems entirely resolved. Changes are showing up on the website within 20 minutes of a deploy (at latest). 
3. The redirect work has wrapped up. Eric and Sean will be working together today on the health check/link script to clean up any remaining busted-ness.

Given all of this, I am closing this issue (though leaving [DOC-297] open for now). 

***[posted via JIRA by Lauren Rother]***
