### ISSUE TITLE
How much space needed to install Riak_TS on ubuntu VirtualBox?  [JIRA: DOC-617]

### ISSUE THREAD

**Issue by Keam** [basho/basho_docs#2228]
Keep trying to install on my Ubuntu16.04 Virtual box. I have 8gb for the VM. when I install Riak_TS (from source). I get the following error ``No space left on device``. How much do I need?

<img width="812" alt="screen shot 2016-08-30 at 6 02 43 pm" src="https://cloud.githubusercontent.com/assets/861222/18108852/51e549ce-6edc-11e6-9309-80d4729b3ce6.png">

**Comment by TheOnlyRew** [comment]
I just pulled down and build from source a copy of Riak TS 1.4.0, and the resulting rel was only about 90MB. All of the dependecy source files and compilation artifacts were closer to 600MB. I'm not sure how much space will be taken during the build process, but I can't image it would be that much more.

That said, I'm not sure this question is well suited to be answered as part of Basho's documentation platform, as we tend to assume users will download our [pre-built packages](http://docs.basho.com/riak/ts/1.3.1/downloads/) rather than building from source. I would recommend reaching out to our [Riak Users mailing list](http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com) for questions regarding building these tools from source. Plenty of Basho engineers monitor that mailing list, so you'll definitely get some good attention and direction there.

**Comment by Keam** [comment]
Thanks I will use the pre-built packages
